language: android
jdk: oraclejdk7

android:
    components:
        - build-tools-21.1.1
        - android-21
        - extra-google-m2repository
        - extra-android-m2repository
        - sys-img-armeabi-v7a-android-21

before_install:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &

before_script:
  - ./ci/android-wait-for-emulator
  - adb shell input keyevent 82 &

notifications:
    email: false
